### PR TITLE
add all types of Cards

### PR DESCRIPTION
**Pull request by hsnice16**
**Before Changes**

No Component was present.

**After Changes**

Card component is present of the following types
- Horizontal Text Card
- Vertical Item Card
- Text Overlay Card
- Dismiss Card with Shadow

Now, File structure is
```
  /
  |
  | -- assets /  jpegs /
  |          | -- captain-america.jpg
  |          | -- eternals.jpg
  |          | -- hulk-bobblehead.jpg
  |          | -- marvel.jpg
  |
  | -- css /
  |       | -- components / Card /
  |       |                | -- card.css
  |       |                | -- dismiss.css
  |       |                | -- horizontal.css
  |       |                | -- textOverlay.css
  |       |                | -- vertical.css
  |       | -- utilities /
  |       |        | -- margin.css
  |       | -- main.css
  |       | -- root.css
  |
  | -- README.md
  | -- app.css
  | -- index.html
```

To see UI of the Cards, check - [https://poshui-components.netlify.app/](https://poshui-components.netlify.app/)

Please review this PR, and give your feedback on **How can I improve the code structure, commit messages, class naming, and UI of the components ?**

Thankyou for reviewing it. 🙏🏻

### CODE REVIEW

**Comment by yash9263** [comment]
LGTM

**Comment by hsnice16** [comment]
@yash9263  
**LGTM** can analyze projects written in Java, Python, JavaScript, TypeScript, C#, Go, C and C++ only. 

** mentioned on their site.

**Comment by yash9263** [comment]
It's just an abbreviation for `looks good to me` this I meant

**Comment by hsnice16** [comment]
Oh! I thought you are talking about tool. My bad, 😅.

**Comment by vashnavichauhan1825** [comment]
everything is good :)

**Pull request merged**
