### PR TITLE
fix checked rating hover

### PR DESCRIPTION
**Pull request by hsnice16**

### CODE REVIEW

**Comment by mikesch803** [comment]
rating is working. Great work!

**Review by mikesch803 — APPROVED** [review]

**Review by sainath7878 — APPROVED** [review]
LGTM.

**Review by zoef-yt — APPROVED** [review]
Good to merge.

**Review by BalajiHarinath — APPROVED** [review]
Looks good to me

**Comment by hsnice16** [comment]
Thank you for reviewing.

**Pull request merged**
