### PR TITLE
add Grid component

### PR DESCRIPTION
**Pull request by hsnice16**
implemented Grid Component.

met the following requirements.
image

This is how UI looks,

- image
- image

### CODE REVIEW

**Review by BalajiHarinath — APPROVED** [review]
Looks good to me.

**Review by Hamza-777 — APPROVED** [review]
All looks good.

**Comment by Hamza-777** [comment]
Just wanted to ask why did you ise minmax.

**Comment by hsnice16** [comment]
> Just wanted to ask why did you ise minmax.

It helps to avoid the Grid Blowout situation.

**Comment by hsnice16** [comment]
Thank you for reviewing.

**Pull request merged**
